application:
  cors:
    allowed-origins: "*"
    allowed-methods: GET, PUT, POST, DELETE, OPTIONS
    allowed-headers: "*"
    exposed-headers: X-app-error
    allow-credentials: true
    max-age: 1800
  elasticsearch:
    targetUri: elasticsearch://localhost:9200
  syncSchedule:
    jobConfig: 30000
  jobHeartbeat:
    jobStatusCheckInterval: 10000

jwt:
  secretKey: secret-key-changeit
  expirationTime: 864000000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test1
    username: admin
    password: admin@1234


server:
  port: 9192

